language: scala

scala:
  - 2.12.11

jdk:
  - oraclejdk11

dist: trusty

before_install:
  - sudo apt-get install graphviz

script:
  - set -e
  - sbt -jvm-opts .travis-jvmopts ++$TRAVIS_SCALA_VERSION clean test scalastyle test:scalastyle
  - sbt -jvm-opts .travis-jvmopts ++$TRAVIS_SCALA_VERSION corenlp/test corenlp/scalastyle
  - mdoc/bin/buildDocs

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: generated-docs/target/mdoc
  on:
    branch: master
