language: scala

scala:
  - 2.12.8

jdk:
  - oraclejdk11

dist: trusty

script:
  - sbt -jvm-opts .travis-jvmopts ++$TRAVIS_SCALA_VERSION clean test scalastyle test:scalastyle
  - sbt -jvm-opts .travis-jvmopts ++$TRAVIS_SCALA_VERSION corenlp/test corenlp/scalastyle
