language: scala

scala:
  - 2.12.8

jdk:
  - oraclejdk8

dist: xenial

script:
  - travis_wait sbt -jvm-opts .travis-jvmopts ++$TRAVIS_SCALA_VERSION clean test scalastyle test:scalastyle
  - sbt -jvm-opts .travis-jvmopts ++$TRAVIS_SCALA_VERSION corenlp/test corenlp/scalastyle
