language: scala

scala:
  - 2.13.3

jdk:
  - oraclejdk11

dist: trusty

before_install:
  - sudo apt-get install graphviz

install:
  - wget https://github.com/lingeringsocket/extjwnl-data-mcr30-2016/archive/main.zip
  - unzip main.zip
  - pushd extjwnl-data-mcr30-2016-main && ./publishLocal.sh && popd

script:
  - set -e
  - sbt -jvm-opts .travis-jvmopts ++$TRAVIS_SCALA_VERSION clean test scalastyle test:scalastyle
  - sbt -jvm-opts .travis-jvmopts ++$TRAVIS_SCALA_VERSION corenlp/test corenlp/scalastyle
#  - mdoc/bin/buildDocs

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: generated-docs/target/mdoc
  on:
    branch: master
